require("dotenv").config({ path: require("path").resolve(__dirname, "../../.env") });
const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
const connectDB = require("../config/db");
const Category = require("../models/Category");
const Question = require("../models/Question");
const User = require("../models/User");

// ─── Seed data (mirrors frontend mock-data.ts) ────────────────────────────────
const CATEGORIES = [
  { slug: "science",    name: "Science",      icon: "🔬", color: "160 84% 44%", description: "Physics, Chemistry, Biology and more",   questionCount: 7 },
  { slug: "geography",  name: "Geography",    icon: "🌍", color: "210 90% 55%", description: "Countries, capitals, landmarks",          questionCount: 7 },
  { slug: "history",    name: "History",      icon: "📜", color: "38 92% 55%",  description: "Ancient to modern world history",         questionCount: 7 },
  { slug: "movies",     name: "Movies",       icon: "🎬", color: "0 72% 55%",   description: "Hollywood, Bollywood, and beyond",        questionCount: 7 },
  { slug: "sports",     name: "Sports",       icon: "⚽", color: "120 60% 45%", description: "Football, cricket, olympics",              questionCount: 49 },
  { slug: "music",      name: "Music",        icon: "🎵", color: "270 70% 60%", description: "Artists, albums, genres",                  questionCount: 7 },
  { slug: "technology", name: "Technology",   icon: "💻", color: "200 80% 50%", description: "Gadgets, coding, innovation",              questionCount: 7 },
  { slug: "literature", name: "Literature",   icon: "📚", color: "30 70% 50%",  description: "Books, authors, poetry",                   questionCount: 7 },
  { slug: "gaming",     name: "Gaming",       icon: "🎮", color: "280 80% 55%", description: "Video games, esports, retro",              questionCount: 7 },
  { slug: "food",       name: "Food & Drink", icon: "🍕", color: "15 85% 55%",  description: "Cuisine, recipes, beverages",              questionCount: 50 },
  { slug: "nature",     name: "Nature",       icon: "🌿", color: "140 70% 40%", description: "Animals, plants, ecosystems",              questionCount: 7 },
  { slug: "art",        name: "Art & Design", icon: "🎨", color: "320 70% 55%", description: "Painting, sculpture, design",              questionCount: 7 },
  { slug: "k-pop",      name: "K-Pop",        icon: "🎤", color: "330 80% 58%", description: "Korean pop, groups, and idols",            questionCount: 7 },
  { slug: "squid-game", name: "Squid Game",   icon: "🦑", color: "142 65% 42%", description: "The Netflix series — trivia and lore",   questionCount: 55 },
  { slug: "pak-dramas", name: "Pak Dramas",   icon: "🎬", color: "24 90% 55%",  description: "Pakistani dramas — iconic stories & characters", questionCount: 71 },
  { slug: "english",    name: "English",      icon: "📘", color: "210 85% 55%", description: "Vocabulary, meanings, and usage",         questionCount: 49 },
  { slug: "urdu",       name: "Urdu",         icon: "📗", color: "152 69% 42%", description: "Urdu vocabulary — meanings and usage",     questionCount: 49 },
  { slug: "logos",      name: "Logos",        icon: "🧠", color: "4 78% 55%",   description: "Logo quiz — identify brands from their logos", questionCount: 32 },
];

const QUESTIONS = {
  science: [
    { text: "What is the chemical symbol for gold?",                       options: ["Go","Gd","Au","Ag"],                        correctIndex: 2   },
    { text: "How many bones are in the adult human body?",                 options: ["196","206","216","186"],                    correctIndex: 1 },
    { text: "What planet is known as the Red Planet?",                     options: ["Venus","Mars","Jupiter","Saturn"],          correctIndex: 1   },
    { text: "What is the speed of light in km/s (approx)?",               options: ["300,000","150,000","500,000","250,000"],    correctIndex: 0   },
    { text: "What gas do plants absorb from the atmosphere?",             options: ["Oxygen","Nitrogen","Carbon Dioxide","Hydrogen"], correctIndex: 2 },
    { text: "What is the hardest natural substance on Earth?",            options: ["Titanium","Diamond","Quartz","Topaz"],      correctIndex: 1 },
    { text: "What is the powerhouse of the cell?",                        options: ["Nucleus","Ribosome","Mitochondria","Golgi body"], correctIndex: 2 },
  ],
  geography: [
    { text: "What is the capital of Australia?",                          options: ["Sydney","Melbourne","Canberra","Brisbane"],  correctIndex: 2 },
    { text: "Which is the longest river in the world?",                   options: ["Amazon","Nile","Yangtze","Mississippi"],    correctIndex: 1   },
    { text: "What country has the most islands?",                         options: ["Indonesia","Philippines","Sweden","Japan"], correctIndex: 2   },
    { text: "Mount Everest is located in which mountain range?",          options: ["Andes","Alps","Rockies","Himalayas"],       correctIndex: 3   },
    { text: "What is the smallest country in the world?",                 options: ["Monaco","Vatican City","San Marino","Liechtenstein"], correctIndex: 1 },
    { text: "Which desert is the largest in the world?",                  options: ["Sahara","Arabian","Gobi","Antarctic"],     correctIndex: 3   },
    { text: "What is the deepest ocean trench?",                          options: ["Tonga Trench","Mariana Trench","Java Trench","Puerto Rico Trench"], correctIndex: 1 },
  ],
  history: [
    { text: "In what year did World War II end?",                         options: ["1943","1944","1945","1946"],                correctIndex: 2   },
    { text: "Who was the first Emperor of Rome?",                         options: ["Julius Caesar","Augustus","Nero","Caligula"], correctIndex: 1 },
    { text: "The French Revolution began in which year?",                 options: ["1776","1789","1799","1804"],                correctIndex: 1 },
    { text: "Who built the Great Wall of China?",                         options: ["Ming Dynasty","Qin Dynasty","Han Dynasty","Multiple Dynasties"], correctIndex: 3 },
    { text: "Which civilization built Machu Picchu?",                     options: ["Maya","Aztec","Inca","Olmec"],              correctIndex: 2   },
    { text: "Who painted the Mona Lisa?",                                 options: ["Michelangelo","Raphael","Da Vinci","Botticelli"], correctIndex: 2 },
    { text: "The Berlin Wall fell in which year?",                        options: ["1987","1988","1989","1990"],                correctIndex: 2   },
  ],
  movies: [
    { text: "Who directed 'The Dark Knight'?",                            options: ["Spielberg","Nolan","Scorsese","Cameron"],   correctIndex: 1   },
    { text: "Which movie won the first Academy Award for Best Picture?",  options: ["Wings","Sunrise","The Jazz Singer","Ben-Hur"], correctIndex: 0 },
    { text: "What year was the original Star Wars released?",             options: ["1975","1977","1979","1980"],                correctIndex: 1 },
    { text: "Who played Iron Man in the MCU?",                            options: ["Chris Evans","Mark Ruffalo","Robert Downey Jr.","Chris Hemsworth"], correctIndex: 2 },
    { text: "What film features the line 'Here's looking at you, kid'?",  options: ["Casablanca","Gone with the Wind","Citizen Kane","Rebecca"], correctIndex: 0 },
    { text: "Which studio produced 'Toy Story'?",                         options: ["DreamWorks","Pixar","Blue Sky","Illumination"], correctIndex: 1 },
    { text: "What is the highest-grossing film of all time (unadjusted)?", options: ["Titanic","Avatar","Avengers: Endgame","The Lion King"], correctIndex: 2 },
  ],
  sports: [
    { text: "Which country won the FIFA World Cup in 2018?", options: ["Germany", "Brazil", "France", "Argentina"], correctIndex: 2 },
    { text: "In cricket, how many players are there in one team on the field?", options: ["9", "10", "11", "12"], correctIndex: 2 },
    { text: "Which tennis tournament is played on grass courts?", options: ["US Open", "French Open", "Wimbledon", "Australian Open"], correctIndex: 2 },
    { text: "In football, how long is a standard match (excluding extra time)?", options: ["80 minutes", "90 minutes", "100 minutes", "120 minutes"], correctIndex: 1 },
    { text: "Which country is known as the birthplace of cricket?", options: ["India", "Australia", "England", "South Africa"], correctIndex: 2 },
    { text: "Who has won the most Ballon d’Or awards (as of recent records)?", options: ["Ronaldo", "Messi", "Neymar", "Mbappé"], correctIndex: 1 },
    { text: "In basketball, how many points is a free throw worth?", options: ["2", "3", "1", "4"], correctIndex: 2 },
    { text: "Which sport uses the term “love” for zero?", options: ["Cricket", "Tennis", "Football", "Hockey"], correctIndex: 1 },
    { text: "Which country hosts the IPL cricket league?", options: ["Australia", "England", "India", "UAE"], correctIndex: 2 },
    { text: "In football, which position primarily guards the goal?", options: ["Defender", "Midfielder", "Goalkeeper", "Striker"], correctIndex: 2 },
    { text: "Which Grand Slam is played on clay courts?", options: ["Wimbledon", "French Open", "US Open", "Australian Open"], correctIndex: 1 },
    { text: "How many overs are there in a T20 cricket match per side?", options: ["10", "20", "30", "50"], correctIndex: 1 },
    { text: "Which NBA player is known as “King James”?", options: ["Kobe Bryant", "LeBron James", "Curry", "Durant"], correctIndex: 1 },
    { text: "Which country has won the most Cricket World Cups?", options: ["India", "Australia", "England", "Pakistan"], correctIndex: 1 },
    { text: "In badminton, what is the object called?", options: ["Ball", "Shuttlecock", "Disc", "Feather"], correctIndex: 1 },
    { text: "Which football club is known as “The Red Devils”?", options: ["Liverpool", "Manchester United", "Arsenal", "Chelsea"], correctIndex: 1 },
    { text: "How many players are on a basketball team on the court?", options: ["4", "5", "6", "7"], correctIndex: 1 },
    { text: "Which country won the FIFA World Cup 2022?", options: ["Brazil", "Argentina", "France", "Germany"], correctIndex: 1 },
    { text: "In cricket, what does LBW stand for?", options: ["Leg Before Wicket", "Long Ball Win", "Left Bat Wicket", "Low Ball Wide"], correctIndex: 0 },
    { text: "Which sport is associated with the Ryder Cup?", options: ["Tennis", "Golf", "Cricket", "Football"], correctIndex: 1 },
    { text: "Which country invented basketball?", options: ["USA", "Canada", "UK", "Australia"], correctIndex: 1 },
    { text: "Which tennis player is known as “King of Clay”?", options: ["Federer", "Nadal", "Djokovic", "Murray"], correctIndex: 1 },
    { text: "In football, how many players are on the field per team?", options: ["9", "10", "11", "12"], correctIndex: 2 },
    { text: "Which sport uses a pommel horse?", options: ["Gymnastics", "Wrestling", "Athletics", "Boxing"], correctIndex: 0 },
    { text: "Which country is dominant in sumo wrestling?", options: ["China", "Japan", "Korea", "Thailand"], correctIndex: 1 },
    { text: "Which sport has the term “birdie”?", options: ["Tennis", "Golf", "Cricket", "Baseball"], correctIndex: 1 },
    { text: "In baseball, how many bases are there?", options: ["3", "4", "5", "6"], correctIndex: 1 },
    { text: "Which country hosts the Tour de France?", options: ["Italy", "France", "Spain", "Germany"], correctIndex: 1 },
    { text: "Which cricketer is known as “Captain Cool”?", options: ["Kohli", "Dhoni", "Rohit", "Smith"], correctIndex: 1 },
    { text: "Which sport uses a net, racket, and shuttle?", options: ["Tennis", "Badminton", "Squash", "Table Tennis"], correctIndex: 1 },
    { text: "Which Olympic sport involves rings, vault, and bars?", options: ["Gymnastics", "Wrestling", "Boxing", "Swimming"], correctIndex: 0 },
    { text: "Which country won Euro 2016?", options: ["Spain", "Portugal", "France", "Germany"], correctIndex: 1 },
    { text: "Which cricket format has 50 overs per side?", options: ["Test", "ODI", "T20", "League"], correctIndex: 1 },
    { text: "Which footballer is known for “Hand of God” goal?", options: ["Messi", "Maradona", "Ronaldo", "Pele"], correctIndex: 1 },
    { text: "Which sport uses a puck?", options: ["Hockey", "Cricket", "Baseball", "Football"], correctIndex: 0 },
    { text: "Which tennis player has most Grand Slam titles (modern era)?", options: ["Federer", "Djokovic", "Nadal", "Murray"], correctIndex: 1 },
    { text: "Which country is famous for rugby dominance?", options: ["India", "New Zealand", "USA", "Japan"], correctIndex: 1 },
    { text: "In cricket, what is a “duck”?", options: ["10 runs", "0 runs", "50 runs", "100 runs"], correctIndex: 1 },
    { text: "Which sport uses gloves and a ring?", options: ["Wrestling", "Boxing", "MMA", "Karate"], correctIndex: 1 },
    { text: "Which country hosted FIFA 2014?", options: ["Germany", "Brazil", "Russia", "Qatar"], correctIndex: 1 },
    { text: "Which sport includes dribbling and slam dunks?", options: ["Football", "Basketball", "Rugby", "Tennis"], correctIndex: 1 },
    { text: "Which country is strong in table tennis globally?", options: ["USA", "China", "India", "UK"], correctIndex: 1 },
    { text: "Which sport is known as “the beautiful game”?", options: ["Cricket", "Football", "Tennis", "Rugby"], correctIndex: 1 },
    { text: "Which cricket stadium is called “Mecca of Cricket”?", options: ["Wankhede", "Lord’s", "MCG", "Eden Gardens"], correctIndex: 1 },
    { text: "Which sport involves a baton relay?", options: ["Swimming", "Athletics", "Cycling", "Boxing"], correctIndex: 1 },
    { text: "Which country won Cricket World Cup 2011?", options: ["Australia", "India", "England", "Pakistan"], correctIndex: 1 },
    { text: "Which sport uses a tee?", options: ["Cricket", "Golf", "Tennis", "Baseball"], correctIndex: 1 },
    { text: "Which player is known for “GOAT” debate in football?", options: ["Neymar", "Messi & Ronaldo", "Mbappé", "Haaland"], correctIndex: 1 },
    { text: "Which sport has “offside rule”?", options: ["Basketball", "Football", "Tennis", "Boxing"], correctIndex: 1 },
  ],
  music: [
    { text: "How many strings does a standard guitar have?",              options: ["4","5","6","7"],                           correctIndex: 2   },
    { text: "Who is known as the 'King of Pop'?",                         options: ["Elvis Presley","Prince","Michael Jackson","James Brown"], correctIndex: 2 },
    { text: "Which band wrote 'Bohemian Rhapsody'?",                      options: ["Led Zeppelin","The Rolling Stones","Queen","The Who"], correctIndex: 2 },
    { text: "What does 'BPM' stand for in music?",                        options: ["Bass Per Measure","Beats Per Minute","Beat Per Melody","Bass Per Minute"], correctIndex: 1 },
    { text: "How many notes are in a standard Western musical scale?",    options: ["5","7","8","12"],                          correctIndex: 1 },
    { text: "Which instrument has 88 keys?",                              options: ["Organ","Harpsichord","Piano","Synthesizer"], correctIndex: 2 },
    { text: "What music genre originated in 1970s New York?",             options: ["Jazz","Hip-Hop","Blues","Reggae"],         correctIndex: 1 },
  ],
  technology: [
    { text: "What does 'HTTP' stand for?",                                 options: ["HyperText Transfer Protocol","High Transfer Text Protocol","Hyper Transfer Text Provider","HyperText Transit Protocol"], correctIndex: 0 },
    { text: "Who co-founded Apple with Steve Jobs?",                       options: ["Bill Gates","Steve Wozniak","Paul Allen","Jony Ive"], correctIndex: 1 },
    { text: "What language is used to style web pages?",                  options: ["HTML","JavaScript","CSS","Python"],        correctIndex: 2   },
    { text: "What does 'GPU' stand for?",                                  options: ["General Processing Unit","Graphics Processing Unit","Gigabit Processing Unit","Global Processing Unit"], correctIndex: 1 },
    { text: "What year was the first iPhone released?",                    options: ["2005","2006","2007","2008"],               correctIndex: 2 },
    { text: "What is the base of the binary number system?",              options: ["8","10","2","16"],                         correctIndex: 2   },
    { text: "Who invented the World Wide Web?",                            options: ["Bill Gates","Tim Berners-Lee","Vint Cerf","Steve Jobs"], correctIndex: 1 },
  ],
  literature: [
    { text: "Who wrote '1984'?",                                           options: ["Aldous Huxley","George Orwell","Ray Bradbury","H.G. Wells"], correctIndex: 1 },
    { text: "Who wrote 'Pride and Prejudice'?",                            options: ["Charlotte Brontë","Mary Shelley","Jane Austen","George Eliot"], correctIndex: 2 },
    { text: "In which Shakespeare play does Hamlet appear?",              options: ["Othello","Hamlet","Macbeth","King Lear"],  correctIndex: 1   },
    { text: "What is the name of Sherlock Holmes' address?",              options: ["10 Downing St","221B Baker St","4 Privet Drive","13 Baker St"], correctIndex: 1 },
    { text: "Who wrote 'The Great Gatsby'?",                               options: ["Ernest Hemingway","F. Scott Fitzgerald","John Steinbeck","William Faulkner"], correctIndex: 1 },
    { text: "Which novel starts with 'Call me Ishmael'?",                 options: ["Moby Dick","Lord Jim","Billy Budd","The Old Man and the Sea"], correctIndex: 0 },
    { text: "What is the first book of the Bible?",                        options: ["Exodus","Leviticus","Genesis","Numbers"],  correctIndex: 2   },
  ],
  gaming: [
    { text: "What year was Minecraft first released?",                    options: ["2008","2009","2010","2011"],               correctIndex: 2 },
    { text: "Which company created Fortnite?",                            options: ["Activision","EA","Epic Games","Ubisoft"],  correctIndex: 2   },
    { text: "What is the best-selling video game of all time?",           options: ["Tetris","GTA V","Minecraft","Wii Sports"], correctIndex: 2 },
    { text: "Who is the main character of 'The Legend of Zelda'?",        options: ["Zelda","Link","Ganon","Epona"],            correctIndex: 1   },
    { text: "In Pokémon, what type is Charizard?",                        options: ["Fire","Fire/Dragon","Fire/Flying","Dragon"], correctIndex: 2 },
    { text: "What franchise features Master Chief?",                       options: ["Gears of War","Halo","Call of Duty","Doom"], correctIndex: 1 },
    { text: "Which gaming company created Mario?",                        options: ["Sega","Atari","Nintendo","Sony"],          correctIndex: 2   },
  ],
  food: [
    { text: "What type of food is shown in the image?", options: ["Noodles", "Spaghetti", "Vermicelli", "Udon"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/spaghetti.png" },
    { text: "This twisted baked snack is called:", options: ["Bagel", "Donut", "Pretzel", "Croissant"], correctIndex: 2, timeLimit: 10, imageUrl: "/uploads/food/pretzel.png" },
    { text: "What dish is shown here?", options: ["Toast sandwich", "Garlic bread", "Bruschetta", "Focaccia"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/garlicbread.png" },
    { text: "This wrapped dish is commonly known as:", options: ["Taco", "Shawarma", "Burrito", "Wrap roll"], correctIndex: 2, timeLimit: 10, imageUrl: "/uploads/food/burrito.png" },
    { text: "Which colorful candy is shown?", options: ["M&M’s", "Gems", "Skittles", "Smarties"], correctIndex: 2, timeLimit: 10, imageUrl: "/uploads/food/skittles.png" },

    { text: "This food belongs to which cuisine?", options: ["Chinese", "Italian", "Mexican", "Indian"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/spaghetti.png" },
    { text: "Garlic bread is most commonly served with which dish?", options: ["Sushi", "Pasta", "Biryani", "Tacos"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/garlicbread.png" },
    { text: "Which cuisine does this dish belong to?", options: ["Italian", "Mexican", "Thai", "Lebanese"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/burrito.png" },
    { text: "Pretzels originated from which region?", options: ["Italy", "Germany", "USA", "France"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/pretzel.png" },
    { text: "What is the tagline associated with this candy?", options: ["Just Do It", "Taste the Rainbow", "Have a Break", "I’m Lovin’ It"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/skittles.png" },

    { text: "Which brand logo is shown in the image?", options: ["Monster", "Red Bull", "Sting", "Gatorade"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/redbull.png" },
    { text: "These spicy rolled chips are popularly known as:", options: ["Doritos", "Takis", "Lays Stix", "Pringles"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/takis.png" },
    { text: "What type of drink is shown here?", options: ["Green Tea Latte (Matcha)", "Mint Shake", "Pistachio Milk", "Avocado Smoothie"], correctIndex: 0, timeLimit: 10, imageUrl: "/uploads/food/matcha.png" },
    { text: "This Middle Eastern dessert is called:", options: ["Baklava", "Kunafa", "Halwa", "Basbousa"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/kunafa.png" },
    { text: "What breakfast dish is shown?", options: ["Waffles", "Pancakes", "Crepes", "Toast stack"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/pancakes.png" },
    { text: "This popular Japanese snack is called:", options: ["Mochi", "Dorayaki", "Taiyaki", "Pancake roll"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/dorayaki.png" },
    { text: "These soft chewy sweets are known as:", options: ["Gummies", "Marshmallows", "Nougat", "Candy floss"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/marshmallows.png" },
    { text: "What type of candy is shown?", options: ["Skittles", "Jelly Beans", "Gems", "Mints"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/jellybeans.png" },
    { text: "This extremely spicy snack challenge is known as:", options: ["Fire Chip", "Hot Bite", "One Chip Challenge", "Ghost Pepper Test"], correctIndex: 2, timeLimit: 10, imageUrl: "/uploads/food/one-chip-challenge.png" },
    { text: "This flaky pastry is called:", options: ["Donut", "Croissant", "Danish", "Puff roll"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/croissant-nutella.png" },

    { text: "This mascot belongs to which snack brand?", options: ["Doritos", "Cheetos", "Kurkure", "Lays"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/cheetos-mascot.png" },
    { text: "This character is associated with which cereal brand?", options: ["Cornflakes", "Chocos", "Coco Pops", "Cheerios"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/chocos-mascot.png" },
    { text: "What is the name of this mascot?", options: ["Tony the Tiger", "Chester Cheetah", "Coco Monkey", "Snap Crackle Pop"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/cheetos-mascot.png" },
    { text: "This cereal is mainly marketed for:", options: ["Adults", "Kids", "Athletes", "Diabetics"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/chocos-mascot.png" },
    { text: "These chewy candies are commonly called:", options: ["Jelly Beans", "Gummies", "Toffees", "Marshmallows"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/gummy-bears.png" },
    { text: "This refreshing drink is typically flavored with:", options: ["Chocolate & Milk", "Mint & Lime", "Coffee & Cream", "Orange & Mango"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/mojito.png" },
    { text: "This protein-rich food is made from:", options: ["Wheat", "Soybeans", "Rice", "Corn"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/fried-tofu.png" },
    { text: "What spread is shown here?", options: ["Peanut Butter", "Honey", "Marmalade", "Butter"], correctIndex: 2, timeLimit: 10, imageUrl: "/uploads/food/marmalade.png" },
    { text: "What dish is shown in the image?", options: ["Pancakes", "Waffles", "Crepes", "French Toast"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/waffles.png" },
    { text: "This sandwich is most commonly associated with which brand?", options: ["McDonald’s", "Burger King", "Subway", "KFC"], correctIndex: 2, timeLimit: 10, imageUrl: "/uploads/food/subway-sandwich.png" },

    { text: "This Japanese dish is called:", options: ["Ramen", "Sushi", "Tempura", "Sashimi"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/sushi.png" },
    { text: "What is the main protein component in this burger?", options: ["Chicken nuggets", "Grilled patty", "Sausage", "Bacon strips"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/burger.png" },
    { text: "This famous dish belongs to which cuisine?", options: ["Chinese", "Italian", "Indian", "Mexican"], correctIndex: 2, timeLimit: 10, imageUrl: "/uploads/food/biryani.png" },
    { text: "This pizza type with pepperoni is most popular in which country?", options: ["France", "Italy", "USA", "Spain"], correctIndex: 2, timeLimit: 10, imageUrl: "/uploads/food/pizza.png" },
    { text: "This dish is traditionally associated with:", options: ["Spain", "Mexico", "Brazil", "Turkey"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/food/taco.png" },

    { text: "What type of pasta is shaped like long thin strands?", options: ["Penne", "Fusilli", "Spaghetti", "Macaroni"], correctIndex: 2 },
    { text: "Which fruit is used to make guacamole?", options: ["Banana", "Avocado", "Mango", "Papaya"], correctIndex: 1 },
    { text: "What is “espresso” best described as?", options: ["Cold coffee drink", "Strong concentrated coffee", "Sweet coffee dessert", "Coffee with milk foam"], correctIndex: 1 },
    { text: "Which dessert is made from layers of cream, coffee, and biscuits?", options: ["Brownie", "Tiramisu", "Cheesecake", "Pudding"], correctIndex: 1 },
    { text: "Which drink is known as “chai” in India?", options: ["Coffee", "Tea", "Milkshake", "Juice"], correctIndex: 1 },
    { text: "Which cuisine is famous for tacos?", options: ["Italian", "Mexican", "Indian", "Thai"], correctIndex: 1 },
    { text: "What is the main ingredient in hummus?", options: ["Lentils", "Chickpeas", "Kidney beans", "Peanuts"], correctIndex: 1 },
    { text: "Which drink is traditionally served cold with mint and lime?", options: ["Mojito", "Cola", "Iced tea", "Lemon soda"], correctIndex: 0 },
    { text: "Which country is known as the origin of pizza?", options: ["USA", "Italy", "France", "Spain"], correctIndex: 1 },
    { text: "What is the main ingredient in tofu?", options: ["Wheat", "Soybeans", "Rice", "Corn"], correctIndex: 1 },
    { text: "What drink is made from coffee and milk?", options: ["Espresso", "Latte", "Americano", "Black Coffee"], correctIndex: 1 },
    { text: "Which food is typically eaten with chopsticks?", options: ["Pizza", "Sushi", "Burger", "Sandwich"], correctIndex: 1 },
    { text: "What is “saffron” primarily used for in cooking?", options: ["Sweetness", "Color and aroma", "Texture", "Thickness"], correctIndex: 1 },
    { text: "Which fast food item is wrapped in a tortilla?", options: ["Burger", "Burrito", "Pizza", "Hotdog"], correctIndex: 1 },
    { text: "What type of cheese is commonly used on pizza?", options: ["Cheddar", "Mozzarella", "Parmesan", "Gouda"], correctIndex: 1 },
  ],
  nature: [
    { text: "What is the fastest land animal?",                           options: ["Lion","Leopard","Cheetah","Greyhound"],    correctIndex: 2   },
    { text: "What is the largest mammal?",                                options: ["Elephant","Blue Whale","Giraffe","Hippo"], correctIndex: 1   },
    { text: "How many legs does a spider have?",                          options: ["6","8","10","12"],                         correctIndex: 1   },
    { text: "What is the process by which plants make food?",             options: ["Respiration","Fermentation","Photosynthesis","Osmosis"], correctIndex: 2 },
    { text: "How many hearts does an octopus have?",                     options: ["1","2","3","4"],                           correctIndex: 2   },
    { text: "What is the tallest type of grass?",                        options: ["Sugarcane","Bamboo","Wheat","Corn"],       correctIndex: 1 },
    { text: "Which is the only bird that can fly backwards?",             options: ["Swallow","Hummingbird","Kingfisher","Swift"], correctIndex: 1 },
  ],
  art: [
    { text: "Who painted the Sistine Chapel ceiling?",                    options: ["Da Vinci","Raphael","Michelangelo","Donatello"], correctIndex: 2 },
    { text: "What art movement did Salvador Dalí belong to?",             options: ["Cubism","Impressionism","Surrealism","Dadaism"], correctIndex: 2 },
    { text: "What colour do you get mixing red and blue?",                options: ["Green","Purple","Orange","Brown"],         correctIndex: 1   },
    { text: "Who created 'The Starry Night'?",                            options: ["Claude Monet","Paul Gauguin","Van Gogh","Cézanne"], correctIndex: 2 },
    { text: "What is the term for a picture made from small tiles?",      options: ["Fresco","Mosaic","Collage","Mural"],       correctIndex: 1 },
    { text: "Which museum houses the Mona Lisa?",                         options: ["Uffizi","Prado","Louvre","Metropolitan"],   correctIndex: 2   },
    { text: "What painting technique involves applying thick layers of paint?", options: ["Watercolour","Impasto","Glazing","Sgraffito"], correctIndex: 1 },
  ],
  "k-pop": [
    { text: "Which company (label) is home to the group BTS?", options: ["SM Entertainment", "YG Entertainment", "HYBE (BigHit)", "JYP Entertainment"], correctIndex: 2 },
    { text: "What does 'K-Pop' stand for?", options: ["Korean Popular music", "Kyoto Pop", "Kinetic Pop", "K-Performance"], correctIndex: 0 },
    { text: "Which girl group released 'How You Like That'?", options: ["TWICE", "BLACKPINK", "(G)I-DLE", "aespa"], correctIndex: 1 },
    { text: "In which city is K-Pop's 'Big 3' traditionally centered?", options: ["Busan", "Incheon", "Seoul", "Daegu"], correctIndex: 2 },
    { text: "What is a common name for passionate K-Pop fans?", options: ["Swifties", "ARMY / fandom names", "Beliebers", "Directioners"], correctIndex: 1 },
    { text: "Which boy group is known for the song 'Sorry, Sorry'?", options: ["BIGBANG", "Super Junior", "EXO", "SHINee"], correctIndex: 1 },
    { text: "What is a 'comeback' in K-Pop?", options: ["A tour only", "A new album or single release cycle", "A disbandment", "A TV drama role"], correctIndex: 1 },
  ],
  "squid-game": [
    // First 21: 15 text (orig Q3–5,9–19) + 6 images at slots 2,6,10,13,16,20 (1-based). Tail: remaining 34 text (orig Q1–2,6–8,20–49).
    { text: "What shape is on the guards' masks?", options: ["Star", "Square / Triangle / Circle", "Diamond", "Cross"], correctIndex: 1 },
    { text: "What is the number of the main character in this scene?", options: ["218", "456", "067", "101"], correctIndex: 1, timeLimit: 5, imageUrl: "/uploads/squid-seed/player-456.png" },
    { text: "Who is Player 001?", options: ["The Front Man", "Oh Il-nam", "Ali", "Sang-woo"], correctIndex: 1 },
    { text: "What is the prize money?", options: ["10 billion won", "45.6 billion won", "100 billion won", "1 billion won"], correctIndex: 1 },
    { text: "Who cheats Ali?", options: ["Gi-hun", "Deok-su", "Sang-woo", "Front Man"], correctIndex: 2 },
    { text: "What game is being played in this scene?", options: ["Tug of War", "Red Light, Green Light", "Marbles", "Glass Bridge"], correctIndex: 1, timeLimit: 6, imageUrl: "/uploads/squid-seed/red-light-doll.png" },
    { text: "What is the final game?", options: ["Tug of War", "Squid Game", "Marbles", "Glass Bridge"], correctIndex: 1 },
    { text: "What color are the guards' uniforms?", options: ["Blue", "Green", "Pink/Red", "Black"], correctIndex: 2 },
    { text: "What color are players' tracksuits?", options: ["Red", "Blue", "Green", "Yellow"], correctIndex: 2 },
    { text: "Which player number does this character have?", options: ["218", "067", "101", "456"], correctIndex: 1, timeLimit: 5, imageUrl: "/uploads/squid-seed/player-067.png" },
    { text: "Who is the Front Man?", options: ["Gi-hun", "Jun-ho's brother", "Sang-woo", "Ali"], correctIndex: 1 },
    { text: "What is the third game?", options: ["Tug of War", "Marbles", "Honeycomb", "Glass Bridge"], correctIndex: 0 },
    { text: "What shape must the player carve out in this scene?", options: ["Star", "Circle", "Triangle", "Depends on assigned shape"], correctIndex: 3, timeLimit: 7, imageUrl: "/uploads/squid-seed/dalgona-players.png" },
    { text: "Who falls during Tug of War?", options: ["Sae-byeok", "Deok-su's team", "Gi-hun", "Ali"], correctIndex: 1 },
    { text: "What happens if you lose a game?", options: ["You retry", "You leave", "You are eliminated (killed)", "You get points"], correctIndex: 2 },
    { text: "What do these symbols represent in the series?", options: ["Player ranks", "Guard hierarchy", "Game levels", "Team divisions"], correctIndex: 1, timeLimit: 7, imageUrl: "/uploads/squid-seed/invitation-symbols.png" },
    { text: "Who is Abdul Ali?", options: ["Player 101", "Player 199", "Player 456", "Player 001"], correctIndex: 1 },
    { text: "What game uses marbles?", options: ["4th game", "1st game", "Final game", "2nd game"], correctIndex: 0 },
    { text: "Who tricks Player 001?", options: ["Sang-woo", "Gi-hun", "Deok-su", "Ali"], correctIndex: 1 },
    { text: "What is the purpose of this structure in the game?", options: ["Living quarters", "Game arena", "Player movement between games", "Control center"], correctIndex: 2, timeLimit: 6, imageUrl: "/uploads/squid-seed/maze-stairs.png" },
    { text: "What is the VIPs' role?", options: ["Players", "Guards", "Spectators betting on games", "Workers"], correctIndex: 2 },
    { text: "What is Seong Gi-hun's player number?", options: ["001", "067", "456", "218"], correctIndex: 2 },
    { text: "What game is played in the first round?", options: ["Tug of War", "Red Light, Green Light", "Marbles", "Glass Bridge"], correctIndex: 1 },
    { text: "Who is Kang Sae-byeok?", options: ["Player 218", "Player 067", "Player 456", "Player 001"], correctIndex: 1 },
    { text: "What is the second game?", options: ["Honeycomb (Dalgona)", "Marbles", "Tug of War", "Glass Bridge"], correctIndex: 0 },
    { text: "Which shape is hardest in honeycomb?", options: ["Circle", "Triangle", "Star", "Umbrella"], correctIndex: 3 },
    { text: "What shape has highest rank among guards?", options: ["Circle", "Triangle", "Square", "Star"], correctIndex: 2 },
    { text: "What weapon do triangle guards carry?", options: ["Knife", "Gun", "Stick", "Rope"], correctIndex: 1 },
    { text: "Who is Hwang Jun-ho?", options: ["Player", "Police officer undercover", "VIP", "Guard"], correctIndex: 1 },
    { text: "Where are the games held?", options: ["City", "Island facility", "School", "Prison"], correctIndex: 1 },
    { text: "What is the glass bridge game about?", options: ["Jumping randomly", "Choosing strong glass panels", "Swimming", "Running"], correctIndex: 1 },
    { text: "Who pushes others in glass bridge?", options: ["Gi-hun", "Deok-su", "Ali", "Il-nam"], correctIndex: 1 },
    { text: "What happens to Deok-su?", options: ["Wins", "Escapes", "Falls from bridge with Mi-nyeo", "Joins guards"], correctIndex: 2 },
    { text: "Who is Han Mi-nyeo?", options: ["Player 101's partner", "Guard", "VIP", "Doctor"], correctIndex: 0 },
    { text: "What do players vote for?", options: ["Prize", "Continue or stop games", "Food", "Teams"], correctIndex: 1 },
    { text: "What happens if majority votes to stop?", options: ["Game continues", "Everyone dies", "Players go home with money split", "Restart"], correctIndex: 2 },
    { text: "What is Gi-hun's personality?", options: ["Ruthless", "Kind-hearted but flawed", "Evil", "Silent"], correctIndex: 1 },
    { text: "What does Gi-hun promise Sae-byeok?", options: ["Money", "Help her family", "Escape", "Food"], correctIndex: 1 },
    { text: "Who dies before final game?", options: ["Sae-byeok", "Gi-hun", "Front Man", "VIP"], correctIndex: 0 },
    { text: "How does Sang-woo die?", options: ["Shot", "Falls", "Suicide during final game", "Poison"], correctIndex: 2 },
    { text: "What symbol is on invitation card?", options: ["Triangle, circle, square", "Star", "Heart", "Arrow"], correctIndex: 0 },
    { text: "What number is Sang-woo?", options: ["001", "067", "218", "456"], correctIndex: 2 },
    { text: "What does the doll detect?", options: ["Heat", "Sound", "Movement", "Light"], correctIndex: 2 },
    { text: "What language do VIPs speak?", options: ["Korean", "English mostly", "Chinese", "Japanese"], correctIndex: 1 },
    { text: "What is inside the piggy bank?", options: ["Food", "Prize money accumulating", "Weapons", "Masks"], correctIndex: 1 },
    { text: "Who organizes the game?", options: ["Government", "Rich elites (VIPs)", "Police", "Players"], correctIndex: 1 },
    { text: "What is the shape of the arena in final game?", options: ["Circle", "Triangle", "Squid shape", "Square"], correctIndex: 2 },
    { text: "What does Front Man do to Jun-ho?", options: ["Saves him", "Arrests him", "Shoots him", "Ignores him"], correctIndex: 2 },
    { text: "What motivates most players?", options: ["Fame", "Debt and money problems", "Revenge", "Fun"], correctIndex: 1 },
    { text: "What happens after Gi-hun wins?", options: ["Spends money", "Becomes rich instantly", "Lives in guilt and doesn't use money", "Leaves country"], correctIndex: 2 },
    { text: "What color is the invitation card?", options: ["Black", "Pink/Red", "Blue", "Green"], correctIndex: 1 },
    { text: "What food is given often?", options: ["Steak", "Eggs and soda", "Rice only", "Bread"], correctIndex: 1 },
    { text: "What do workers harvest from bodies?", options: ["Blood", "Organs illegally", "Clothes", "Weapons"], correctIndex: 1 },
    { text: "What does Gi-hun dye his hair at the end?", options: ["Black", "Blonde", "Red", "Blue"], correctIndex: 2 },
    { text: "What does Gi-hun decide at the end?", options: ["Leave country", "Rejoin games", "Turn back to confront organizers", "Quit life"], correctIndex: 2 },
  ],
  "pak-dramas": [
    { text: "Which drama features Mir Hadi & Umera Ahmed storyline?", options: ["Humsafar", "Khaani", "Zindagi Gulzar Hai", "Mere Paas Tum Ho"], correctIndex: 1 },
    { text: "In Humsafar, why do Khirad and Ashar separate?", options: ["Career issues", "Family misunderstanding", "Financial problems", "Infidelity"], correctIndex: 1 },
    { text: "Who plays Kashaf in Zindagi Gulzar Hai?", options: ["Mahira Khan", "Sanam Saeed", "Sajal Aly", "Ayeza Khan"], correctIndex: 1 },
    { text: "In Mere Paas Tum Ho, what causes the main conflict?", options: ["Business rivalry", "Love triangle and betrayal", "Family politics", "Crime"], correctIndex: 1 },
    { text: "What type of relationship dynamic is MOST likely shown here?", options: ["Light comedy", "Toxic romance / intense conflict", "Friendship", "Family bonding"], correctIndex: 1, imageUrl: "/uploads/pak-dramas-seed/pak-01-couple-intense.png" },
    { text: "Which drama is based on honor killing theme?", options: ["Udaari", "Sang-e-Mar Mar", "Sang-e-Mah", "Diyar-e-Dil"], correctIndex: 2 },
    { text: "In Khaani, what is the turning point?", options: ["Marriage", "Murder of Khaani’s brother", "Court case", "Kidnapping"], correctIndex: 1 },
    { text: "What does this kind of cast poster usually indicate?", options: ["Comedy drama", "Ensemble family drama with multiple arcs", "Horror", "Documentary"], correctIndex: 1, imageUrl: "/uploads/pak-dramas-seed/pak-02-cast-black.png" },
    { text: "Which drama highlights child abuse issues?", options: ["Udaari", "Cheekh", "Ranjha Ranjha Kardi", "Ishqiya"], correctIndex: 0 },
    { text: "Who is the lead male in Ibn-e-Hayat?", options: ["Humayun Saeed", "Imran Abbas", "Mikaal Zulfiqar", "Ahsan Khan"], correctIndex: 3 },
    { text: "In Cheekh, what drives the story forward?", options: ["Revenge for murder", "Political power", "Business loss", "Family drama"], correctIndex: 0 },
    { text: "What genre is MOST likely for this drama?", options: ["Sci-fi", "Romantic thriller / family drama", "Fantasy", "Sports"], correctIndex: 1, imageUrl: "/uploads/pak-dramas-seed/pak-04-ary-promo.png" },
    { text: "Which drama features the character Parizaad?", options: ["Parizaad", "Khuda Aur Mohabbat", "Sinf-e-Aahan", "Ishq Jalebi"], correctIndex: 0 },
    { text: "What phase of the story does this scene MOST likely represent?", options: ["Conflict peak", "Revenge arc", "Early romance / peaceful phase", "Tragic ending"], correctIndex: 2, imageUrl: "/uploads/pak-dramas-seed/pak-03-happy-couple.png" },
    { text: "What is Parizaad’s biggest struggle?", options: ["Wealth", "Appearance & self-worth", "Love triangle", "Career"], correctIndex: 1 },
    { text: "Which drama shows female empowerment in army training?", options: ["Sinf-e-Aahan", "Ehd-e-Wafa", "Alpha Bravo Charlie", "Diyar-e-Dil"], correctIndex: 0 },
    { text: "What is the central conflict usually in such dramas?", options: ["Career struggles", "Love triangle / betrayal", "War", "Crime investigation"], correctIndex: 1, imageUrl: "/uploads/pak-dramas-seed/pak-05-urdu-title.png" },
    { text: "In Ehd-e-Wafa, what binds the main characters?", options: ["Family", "Friendship & military academy", "Politics", "Business"], correctIndex: 1 },
    { text: "Who is known as “Chaudhry Shabbir” in Mere Paas Tum Ho?", options: ["Adnan Siddiqui", "Humayun Saeed", "Noman Ijaz", "Firdous Jamal"], correctIndex: 2 },
    { text: "What storyline is MOST likely happening here?", options: ["Wedding celebration", "Forced marriage / emotional tension", "Comedy sequence", "Flashback"], correctIndex: 1, imageUrl: "/uploads/pak-dramas-seed/pak-06-bride.png" },
    { text: "Which drama gained viral fame for dialogue “Do takay ki aurat”?", options: ["Mere Paas Tum Ho", "Khaani", "Humsafar", "Udaari"], correctIndex: 0 },
    { text: "In Khuda Aur Mohabbat, what is the core theme?", options: ["Revenge", "Spiritual love vs worldly love", "Politics", "Crime"], correctIndex: 1 },
    { text: "What role does such a character MOST often play?", options: ["Villain mastermind", "Central emotional lead", "Comic relief", "Side character"], correctIndex: 1, imageUrl: "/uploads/pak-dramas-seed/pak-07-female-closeup.png" },
    { text: "Which actor played Farhad in Khuda Aur Mohabbat 3?", options: ["Feroze Khan", "Bilal Abbas", "Ahad Raza Mir", "Imran Ashraf"], correctIndex: 0 },
    { text: "In Ranjha Ranjha Kardi, what is the main focus?", options: ["Wealth", "Social inequality & obsession", "Politics", "Revenge"], correctIndex: 1 },
    { text: "What is being emphasized in this type of image?", options: ["Action sequence", "Character styling & social status", "Crime plot", "Political theme"], correctIndex: 1, imageUrl: "/uploads/pak-dramas-seed/pak-08-fashion-portraits.png" },
    { text: "Which drama features Saba Qamar in a bold role?", options: ["Baaghi", "Udaari", "Cheekh", "Parizaad"], correctIndex: 0 },
    { text: "In Baaghi, whose life is the story based on?", options: ["Actress", "Social media personality (Qandeel Baloch)", "Politician", "Singer"], correctIndex: 1 },
    { text: "What theme is MOST strongly represented here?", options: ["Comedy", "Family conflict & authority dynamics", "Romance", "Friendship"], correctIndex: 1, imageUrl: "/uploads/pak-dramas-seed/pak-09-slap-scene.png" },
    { text: "Which drama features Danish and Mehwish?", options: ["Mere Paas Tum Ho", "Khaani", "Humsafar", "Cheekh"], correctIndex: 0 },
    { text: "What role is this character MOST likely to play?", options: ["Villain", "Romantic lead / protagonist", "Comic sidekick", "Background extra"], correctIndex: 1, imageUrl: "/uploads/pak-dramas-seed/pak-10-male-portrait.png" },
    { text: "In Ishq Jalebi, what tone dominates the drama?", options: ["Tragic", "Romantic comedy", "Horror", "Thriller"], correctIndex: 1 },
    { text: "Which drama revolves around corporate rivalry?", options: ["Jackson Heights", "Jalan", "Zindagi Gulzar Hai", "Diyar-e-Dil"], correctIndex: 2 },
    { text: "What drives the story in such setups?", options: ["Business", "Female rivalry / jealousy", "War", "Science"], correctIndex: 1, imageUrl: "/uploads/pak-dramas-seed/pak-11-female-rivalry.png" },
    { text: "Who played Haider in Raqs-e-Bismil?", options: ["Imran Ashraf", "Bilal Abbas", "Feroze Khan", "Ahad Raza Mir"], correctIndex: 0 },
    { text: "In Raqs-e-Bismil, what is Haider’s hidden passion?", options: ["Music", "Dance", "Writing", "Acting"], correctIndex: 1 },
    { text: "What kind of storyline is MOST likely?", options: ["Corporate rivalry", "Cultural romance / arranged marriage", "Crime thriller", "Fantasy"], correctIndex: 1, imageUrl: "/uploads/pak-dramas-seed/pak-12-couple-traditional.png" },
    { text: "Which drama focuses on toxic marriage?", options: ["Jalan", "Humsafar", "Udaari", "Ehd-e-Wafa"], correctIndex: 0 },
    { text: "In Diyar-e-Dil, what theme dominates?", options: ["War", "Family relationships & forgiveness", "Crime", "Politics"], correctIndex: 1 },
    { text: "What tone does this drama MOST likely have?", options: ["Lighthearted", "Dark, serious, emotional conflict", "Comedy", "Musical"], correctIndex: 1, imageUrl: "/uploads/pak-dramas-seed/pak-13-dark-cast.png" },
    { text: "Which drama includes university romance turning into marriage struggles?", options: ["Humsafar", "Zindagi Gulzar Hai", "Cheekh", "Udaari"], correctIndex: 1 },
    { text: "In Sang-e-Mah, what is central?", options: ["Romance", "Tribal justice & revenge", "Comedy", "Corporate life"], correctIndex: 1 },
    { text: "Which drama features Ahad Raza Mir & Sajal Aly together?", options: ["Yakeen Ka Safar", "Parizaad", "Cheekh", "Baaghi"], correctIndex: 0 },
    { text: "What narrative structure is shown here?", options: ["Single timeline", "Parallel love stories / multiple arcs", "Documentary", "Game show"], correctIndex: 1, imageUrl: "/uploads/pak-dramas-seed/pak-14-split-love.png" },
    { text: "In Yakeen Ka Safar, what is the core theme?", options: ["Revenge", "Healing & personal growth", "Politics", "Crime"], correctIndex: 1 },
    { text: "Which drama is set around media industry struggles?", options: ["Baaghi", "Jalan", "Jackson Heights", "Ishqiya"], correctIndex: 3 },
    { text: "In Ishqiya, what complicates relationships?", options: ["Money", "Jealousy & love triangle", "Politics", "Crime"], correctIndex: 1 },
    { text: "Which drama showcases rural life & culture strongly?", options: ["Sang-e-Mar Mar", "Cheekh", "Parizaad", "Jalan"], correctIndex: 0 },
    { text: "In Sang-e-Mar Mar, what drives conflict?", options: ["Wealth", "Tribal honor & traditions", "Love triangle", "Career"], correctIndex: 1 },

    { text: "This drama featuring Sajal Aly and Ahad Raza Mir is:", options: ["Yakeen Ka Safar", "Sinf-e-Aahan", "Alif", "Aangan"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-15-sinf-e-aahan.png" },
    { text: "This emotional drama starring Saba Qamar is:", options: ["Cheekh", "Baaghi", "Digest Writer", "Fraud"], correctIndex: 0, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-16-cheekh.png" },
    { text: "This drama featuring Yumna Zaidi and Wahaj Ali is:", options: ["Ishq Jalebi", "Tere Bin", "Dil Na Umeed To Nahi", "Pyar Ke Sadqay"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-17-tere-bin.png" },
    { text: "This drama titled Mere Humsafar stars which actor?", options: ["Feroze Khan", "Farhan Saeed", "Imran Abbas", "Bilal Abbas"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-18-mere-humsafar.png" },
    { text: "This popular HUM TV drama is known as:", options: ["Ishqiya", "Fraud", "Alif Allah Aur Insaan", "Raqs-e-Bismil"], correctIndex: 2, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-19-alif-allah-aur-insaan.png" },
    { text: "This drama with a faith-based storyline is:", options: ["Khuda Aur Mohabbat", "Alif Allah Aur Insaan", "Noor", "Zindagi Gulzar Hai"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-20-alif-allah-faith.png" },
    { text: "This scene featuring a knife became viral from which drama?", options: ["Suno Chanda", "Ishq Jalebi", "Pyar Ke Sadqay", "Ranjha Ranjha Kardi"], correctIndex: 2, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-21-pyar-ke-sadqay-knife.png" },
    { text: "This wedding scene is from which light-hearted drama?", options: ["Suno Chanda", "Chupke Chupke", "Ishq Jalebi", "Hum Tum"], correctIndex: 0, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-22-suno-chanda.png" },
    { text: "This drama featuring a love triangle is:", options: ["Tere Bin", "Ishqiya", "Fraud", "Sinf-e-Aahan"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-23-ishqiya.png" },
    { text: "This drama titled Hum Kahan Ke Sachay Thay stars:", options: ["Mahira Khan", "Sajal Aly", "Hania Aamir", "Iqra Aziz"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-24-hkkst.png" },

    { text: "This scene is from a drama known for portraying which theme?", options: ["Comedy romance", "Crime & revenge", "Rural gangster life", "Corporate drama"], correctIndex: 2, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-25-rural-theme.png" },
    { text: "The male lead in this drama belongs to which background?", options: ["Business family", "Religious household", "Political family", "Army background"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-26-raqs-e-bismil.png" },
    { text: "This character is known for:", options: ["Dual personality", "Revenge arc", "Love triangle conflict", "Comedy role"], correctIndex: 2, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-27-dual-look.png" },
    { text: "This drama is most famous for which element?", options: ["Comedy", "Emotional betrayal storyline", "Horror theme", "Action scenes"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-28-mere-paas-tum-ho.png" },
    { text: "This drama gained popularity mainly due to:", options: ["Action scenes", "Strong chemistry of leads", "Political plot", "Mystery thriller"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-29-zgh-bench.png" },
    { text: "This drama revolves around:", options: ["Family comedy", "Toxic relationships", "College life", "Historical events"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-30-intense-couple.png" },
    { text: "The central conflict in this drama is:", options: ["Friendship vs love", "Love vs ego", "Career vs family", "Tradition vs modern life"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-31-dramatic-couple.png" },
    { text: "This scene mainly represents:", options: ["Romantic tension", "Family conflict", "Workplace drama", "Comedy moment"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-32-family-scene.png" },
    { text: "This drama is best categorized as:", options: ["Light comedy", "Romantic tragedy", "Thriller", "Documentary"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-33-emotional-pair.png" },
    { text: "This character is typically portrayed as:", options: ["Comic relief", "Villain / grey character", "Sidekick", "Romantic hero"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-34-serious-male.png" },
    { text: "This character arc mainly focuses on:", options: ["Revenge", "Self-growth", "Comedy", "Crime solving"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-35-female-arc.png" },
    { text: "This character most likely represents:", options: ["Comic role", "Family elder with authority", "Romantic lead", "Villain mastermind"], correctIndex: 1, timeLimit: 10, imageUrl: "/uploads/pak-dramas-seed/pak-36-elder-woman.png" },
  ],
  english: [
    { text: "“Meticulous” means:", options: ["Careless", "Very detailed and careful", "Angry", "Quick"], correctIndex: 1 },
    { text: "What does “abundant” mean?", options: ["Rare", "Plenty", "Empty", "Small"], correctIndex: 1 },
    { text: "“He was hesitant.” Means:", options: ["Confident", "Unsure", "Angry", "Fast"], correctIndex: 1 },
    { text: "“Fragile” refers to something:", options: ["Strong", "Breakable", "Heavy", "Large"], correctIndex: 1 },
    { text: "“Obsolete” means:", options: ["Modern", "Outdated", "Fast", "Strong"], correctIndex: 1 },
    { text: "“She was exhausted.” Means:", options: ["Energetic", "Very tired", "Happy", "Angry"], correctIndex: 1 },
    { text: "“Zealous” means:", options: ["Lazy", "Passionate / enthusiastic", "Weak", "Calm"], correctIndex: 1 },
    { text: "Choose the correct synonym of “rapid”:", options: ["Slow", "Quick", "Weak", "Quiet"], correctIndex: 1 },
    { text: "“Ambiguous” means:", options: ["Clear", "Confusing / multiple meanings", "Loud", "Honest"], correctIndex: 1 },
    { text: "“Generous” means:", options: ["Selfish", "Giving", "Angry", "Lazy"], correctIndex: 1 },
    { text: "“Erratic” means:", options: ["Stable", "Unpredictable", "Calm", "Slow"], correctIndex: 1 },
    { text: "“He was furious.” Means:", options: ["Happy", "Extremely angry", "Calm", "Tired"], correctIndex: 1 },
    { text: "“Deter” means:", options: ["Encourage", "Discourage", "Ignore", "Repeat"], correctIndex: 1 },
    { text: "“Ancient” means:", options: ["New", "Old", "Fast", "Bright"], correctIndex: 1 },
    { text: "“Candid” means:", options: ["Honest", "Fake", "Loud", "Weak"], correctIndex: 0 },
    { text: "“He gave a vague answer.” Means:", options: ["Clear", "Unclear", "Loud", "Honest"], correctIndex: 1 },
    { text: "“Yield” means:", options: ["Resist", "Give way / produce", "Fight", "Hide"], correctIndex: 1 },
    { text: "“Resilient” means:", options: ["Weak", "Able to recover quickly", "Slow", "Quiet"], correctIndex: 1 },
    { text: "“She is very diligent.” Means:", options: ["Lazy", "Hardworking", "Careless", "Funny"], correctIndex: 1 },
    { text: "“Apathy” means:", options: ["Interest", "Lack of interest", "Anger", "Fear"], correctIndex: 1 },
    { text: "“Futile” means:", options: ["Useful", "Useless", "Fast", "Strong"], correctIndex: 1 },
    { text: "“Cautious” means:", options: ["Careless", "Careful", "Angry", "Lazy"], correctIndex: 1 },
    { text: "“Subtle” means:", options: ["Obvious", "Slight / not obvious", "Loud", "Fast"], correctIndex: 1 },
    { text: "“Pragmatic” means:", options: ["Emotional", "Practical", "Lazy", "Angry"], correctIndex: 1 },
    { text: "“She gave a genuine smile.” Means:", options: ["Fake", "Real", "Loud", "Weak"], correctIndex: 1 },
    { text: "“Lucid” means:", options: ["Clear", "Confusing", "Loud", "Weak"], correctIndex: 0 },
    { text: "“Scarce” means:", options: ["Plenty", "Rare / limited", "Big", "Bright"], correctIndex: 1 },
    { text: "“Hostile” is closest to:", options: ["Friendly", "Aggressive", "Calm", "Soft"], correctIndex: 1 },
    { text: "“Omit” means:", options: ["Include", "Leave out", "Add", "Build"], correctIndex: 1 },
    { text: "“He made a clever move.” Means:", options: ["Smart", "Stupid", "Slow", "Weak"], correctIndex: 0 },
    { text: "“Elated” means:", options: ["Sad", "Extremely happy", "Angry", "Tired"], correctIndex: 1 },
    { text: "“Novice” means:", options: ["Expert", "Beginner", "Leader", "Teacher"], correctIndex: 1 },
    { text: "“Exaggerate” means:", options: ["Minimize", "Overstate", "Explain", "Hide"], correctIndex: 1 },
    { text: "“Tedious” means:", options: ["Exciting", "Boring / repetitive", "Fast", "Easy"], correctIndex: 1 },
    { text: "“Hostility” means:", options: ["Friendship", "Hatred", "Peace", "Joy"], correctIndex: 1 },
    { text: "“Infer” means:", options: ["Suggest", "Conclude from evidence", "Hide", "Repeat"], correctIndex: 1 },
    { text: "“Conceal” means:", options: ["Show", "Hide", "Break", "Build"], correctIndex: 1 },
    { text: "“Ample” means:", options: ["Small", "Enough / more than enough", "Weak", "Rare"], correctIndex: 1 },
    { text: "“Reluctant” means:", options: ["Eager", "Unwilling", "Happy", "Fast"], correctIndex: 1 },
    { text: "“The movie was thrilling.” Means:", options: ["Boring", "Exciting", "Slow", "Sad"], correctIndex: 1 },
    { text: "“Validate” means:", options: ["Reject", "Confirm / prove true", "Ignore", "Break"], correctIndex: 1 },
    { text: "“He is arrogant.” Means:", options: ["Humble", "Proud in a negative way", "Shy", "Kind"], correctIndex: 1 },
    { text: "“Gratify” means:", options: ["Annoy", "Please / satisfy", "Break", "Hide"], correctIndex: 1 },
    { text: "“Wary” means:", options: ["Careless", "Cautious", "Happy", "Angry"], correctIndex: 1 },
    { text: "“Brief meeting” means:", options: ["Long", "Short", "Loud", "Serious"], correctIndex: 1 },
    { text: "Opposite of “expand”:", options: ["Grow", "Shrink", "Increase", "Extend"], correctIndex: 1 },
    { text: "“Difficult” synonym:", options: ["Easy", "Hard", "Clear", "Light"], correctIndex: 1 },
    { text: "“Benevolent” means:", options: ["Evil", "Kind and generous", "Lazy", "Weak"], correctIndex: 1 },
    { text: "“Imply” means:", options: ["To say directly", "To suggest indirectly", "To lie", "To repeat"], correctIndex: 1 },
  ],
  urdu: [
    { text: "What does “فرسودہ” mean?", options: ["Modern", "Outdated / worn out", "Fast", "Strong"], correctIndex: 1 },
    { text: "What does “خوشحال” mean?", options: ["Sad", "Prosperous / happy", "Weak", "Silent"], correctIndex: 1 },
    { text: "“ہچکچانا” means:", options: ["To be confident", "To hesitate", "To run", "To laugh"], correctIndex: 1 },
    { text: "What does “خاموش” mean?", options: ["Loud", "Silent", "Bright", "Fast"], correctIndex: 1 },
    { text: "What does “مضبوط اعصاب” mean?", options: ["Weak personality", "Emotionally strong / resilient", "Slow", "Silent"], correctIndex: 1 },
    { text: "“محنتی” refers to someone who is:", options: ["Lazy", "Hardworking", "Angry", "Silent"], correctIndex: 1 },
    { text: "What does “بے ترتیب” mean?", options: ["Organized", "Unpredictable / irregular", "Calm", "Slow"], correctIndex: 1 },
    { text: "What does “وسیع” mean?", options: ["Narrow", "Wide / spacious", "Small", "Hard"], correctIndex: 1 },
    { text: "“محتاط” refers to someone who is:", options: ["Careless", "Careful / cautious", "Fast", "Angry"], correctIndex: 1 },
    { text: "What does “نایاب” mean?", options: ["Common", "Rare", "Big", "Bright"], correctIndex: 1 },
    { text: "What does “غمگین” mean?", options: ["Happy", "Sad", "Fast", "Brave"], correctIndex: 1 },
    { text: "“باریک بین” describes a person who is:", options: ["Careless", "Detail-oriented", "Angry", "Lazy"], correctIndex: 1 },
    { text: "What does “مبہم” mean?", options: ["Clear", "Unclear / vague", "Loud", "Honest"], correctIndex: 1 },
    { text: "“چالاک” means:", options: ["Foolish", "Clever / smart", "Lazy", "Sad"], correctIndex: 1 },
    { text: "What does “پوشیدہ” mean?", options: ["Visible", "Hidden", "Loud", "Fast"], correctIndex: 1 },
    { text: "“تھکا ہوا” means:", options: ["Energetic", "Tired", "Happy", "Angry"], correctIndex: 1 },
    { text: "What does “بے فائدہ” mean?", options: ["Useful", "Useless / futile", "Fast", "Strong"], correctIndex: 1 },
    { text: "“سنجیدہ” means:", options: ["Funny", "Serious", "Weak", "Angry"], correctIndex: 1 },
    { text: "What does “دشمنی” mean?", options: ["Friendship", "Enmity / hostility", "Peace", "Joy"], correctIndex: 1 },
    { text: "What does “بہادر” mean?", options: ["Weak", "Brave", "Quiet", "Fast"], correctIndex: 1 },
    { text: "“عملی” means:", options: ["Emotional", "Practical", "Lazy", "Angry"], correctIndex: 1 },
    { text: "What does “دلچسپ” mean?", options: ["Boring", "Interesting", "Slow", "Hard"], correctIndex: 1 },
    { text: "What does “صاف” (opposite) mean?", options: ["Bright", "Dirty", "Soft", "Light"], correctIndex: 1 },
    { text: "“ذہین” describes someone who is:", options: ["Foolish", "Intelligent", "Slow", "Weak"], correctIndex: 1 },
    { text: "What does “اشارہ کرنا” mean?", options: ["To say directly", "To hint / suggest indirectly", "To lie", "To repeat"], correctIndex: 1 },
    { text: "What does “مختصر” mean?", options: ["Long", "Short / brief", "Difficult", "Bright"], correctIndex: 1 },
    { text: "“مبالغہ کرنا” means:", options: ["To reduce", "To exaggerate", "To explain", "To hide"], correctIndex: 1 },
    { text: "What does “باریک” mean?", options: ["Thick", "Thin / subtle", "Loud", "Fast"], correctIndex: 1 },
    { text: "What does “مہربان” mean?", options: ["Cruel", "Kind / compassionate", "Lazy", "Weak"], correctIndex: 1 },
    { text: "“نظر انداز کرنا” means:", options: ["Include", "Ignore / omit", "Add", "Build"], correctIndex: 1 },
    { text: "What does “غصہ” mean?", options: ["Happiness", "Anger / rage", "Calm", "Smile"], correctIndex: 1 },
    { text: "What does “حقیقی” mean?", options: ["Fake", "Real / genuine", "Loud", "Weak"], correctIndex: 1 },
    { text: "What does “نو آموز” mean?", options: ["Expert", "Beginner", "Leader", "Teacher"], correctIndex: 1 },
    { text: "What does “بے حسی” mean?", options: ["Interest", "Lack of interest / apathy", "Anger", "Fear"], correctIndex: 1 },
    { text: "“صاف گو” means:", options: ["Dishonest", "Honest / frank", "Loud", "Weak"], correctIndex: 1 },
    { text: "What does “مشکل” mean?", options: ["Easy", "Difficult", "Light", "Simple"], correctIndex: 1 },
    { text: "What does “نتیجہ اخذ کرنا” mean?", options: ["To suggest", "To conclude / infer", "To hide", "To repeat"], correctIndex: 1 },
    { text: "“مغرور” means:", options: ["Humble", "Arrogant", "Calm", "Silent"], correctIndex: 1 },
    { text: "What does “وسیع” (contextual) mean?", options: ["Tight", "Broad / extensive", "Small", "Hard"], correctIndex: 1 },
    { text: "What does “دلیر” mean?", options: ["Weak", "Brave", "Quiet", "Slow"], correctIndex: 1 },
    { text: "What does “اکتا دینے والا” mean?", options: ["Exciting", "Boring / tiring", "Fast", "Easy"], correctIndex: 1 },
    { text: "What does “واضح” mean?", options: ["Clear", "Confusing", "Loud", "Weak"], correctIndex: 0 },
    { text: "What does “چپ” mean?", options: ["Loud", "Silent", "Bright", "Fast"], correctIndex: 1 },
    { text: "What does “ہوشیار” mean?", options: ["Foolish", "Smart / alert", "Lazy", "Weak"], correctIndex: 1 },
    { text: "What does “اداس” mean?", options: ["Happy", "Sad", "Fast", "Brave"], correctIndex: 1 },
    { text: "What does “سست” mean?", options: ["Fast", "Lazy / slow", "Smart", "Strong"], correctIndex: 1 },
    { text: "What does “خوش” mean?", options: ["Angry", "Happy", "Weak", "Silent"], correctIndex: 1 },
    { text: "What does “تیز” mean?", options: ["Slow", "Fast / sharp", "Weak", "Calm"], correctIndex: 1 },
    { text: "What does “نرم” mean?", options: ["Hard", "Soft", "Loud", "Fast"], correctIndex: 1 },
  ],
  logos: [
    {
      text: "This global beverage brand is known for its rivalry with Coca-Cola. Which logo is this?",
      options: ["Coca-Cola", "Pepsi", "Sprite", "Fanta"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-01-pepsi.png",
    },
    {
      text: "This brand is famous for coffee and its green mermaid logo. Which company is it?",
      options: ["Costa", "Starbucks", "Nescafé", "Dunkin"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-02-starbucks.png",
    },
    {
      text: "This company manufactures airplanes and is a major competitor to Airbus. Identify the logo.",
      options: ["NASA", "Boeing", "SpaceX", "Lockheed Martin"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-03-boeing.png",
    },
    {
      text: "This luxury fashion brand is known for double “C” initials. Which brand is this?",
      options: ["Gucci", "Chanel", "Prada", "Dior"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-04-chanel.png",
    },
    {
      text: "This pizza chain uses a domino tile in its logo. Which brand is it?",
      options: ["Pizza Hut", "Domino’s", "Papa John’s", "Subway"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-05-dominos.png",
    },
    {
      text: "This personal care brand is known for soap and a bird symbol. Identify it.",
      options: ["Lux", "Dove", "Nivea", "Pears"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-06-dove.png",
    },
    {
      text: "This luxury Italian brand features interlocking “G” letters. Which brand is it?",
      options: ["Louis Vuitton", "Gucci", "Versace", "Armani"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-07-gucci.png",
    },
    {
      text: "This clothing brand is famous for a crocodile logo. Which brand is this?",
      options: ["Puma", "Nike", "Lacoste", "Adidas"],
      correctIndex: 2,
      imageUrl: "/uploads/logos-seed/logo-08-lacoste.png",
    },
    {
      text: "This fast-food chain is known for golden arches and burgers worldwide. Identify it.",
      options: ["KFC", "Burger King", "McDonald’s", "Subway"],
      correctIndex: 2,
      imageUrl: "/uploads/logos-seed/logo-09-mcdonalds.png",
    },
    {
      text: "This American bank is known for its red logo and stagecoach symbol. Which brand is it?",
      options: ["Chase", "Bank of America", "Wells Fargo", "Citibank"],
      correctIndex: 2,
      imageUrl: "/uploads/logos-seed/logo-10-wellsfargo.png",
    },
    {
      text: "This snack brand features a mustached mascot and is known for chips in a tube. Which is it?",
      options: ["Lays", "Doritos", "Pringles", "Cheetos"],
      correctIndex: 2,
      imageUrl: "/uploads/logos-seed/logo-11-pringles.png",
    },
    {
      text: "This ice cream brand uses a heart-shaped swirl logo and is popular in India. Identify it.",
      options: ["Baskin Robbins", "Kwality Walls", "Amul", "Cornetto"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-12-kwality-walls.png",
    },
    {
      text: "This luxury car brand uses a double “R” emblem and is known for premium vehicles. Which brand?",
      options: ["Bentley", "Rolls-Royce", "Mercedes", "BMW"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-13-rolls-royce.png",
    },
    {
      text: "This luxury fashion brand uses “LV” initials and a monogram pattern. Identify it.",
      options: ["Gucci", "Louis Vuitton", "Prada", "Dior"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-14-louis-vuitton.png",
    },
    {
      text: "This instant noodle brand is extremely popular in Asia and uses a red-yellow logo. Which is it?",
      options: ["Top Ramen", "Maggi", "Knorr", "Yippee"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-15-maggi.png",
    },
    {
      text: "This premium ice cream brand uses a golden “M” in a circle. Which brand is this?",
      options: ["Cornetto", "Magnum", "Walls", "Baskin Robbins"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-16-magnum.png",
    },
    {
      text: "This global food company uses a bird nest logo symbolizing care and nutrition. Identify it.",
      options: ["Kellogg’s", "Nestlé", "Danone", "Amul"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-17-nestle.png",
    },
    {
      text: "This Indian fashion retail brand uses a stylish “W” as its logo. Which brand is it?",
      options: ["Zara", "Westside", "H&M", "Pantaloons"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-18-westside.png",
    },
    {
      text: "This fast-food brand features the face of its founder, known for fried chicken. Identify it.",
      options: ["McDonald’s", "Burger King", "KFC", "Subway"],
      correctIndex: 2,
      imageUrl: "/uploads/logos-seed/logo-19-kfc.png",
    },
    {
      text: "This television network is one of Pakistan’s most popular entertainment channels. Which logo is this?",
      options: ["ARY Digital", "Hum TV", "Geo TV", "PTV"],
      correctIndex: 2,
      imageUrl: "/uploads/logos-seed/logo-20-geo-tv.png",
    },
    {
      text: "This brand is known for online jewelry shopping in India and uses a stylized “B” logo. Which brand?",
      options: ["Tanishq", "Bluestone", "Kalyan Jewellers", "Malabar Gold"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-21-bluestone.png",
    },
    {
      text: "This brand focuses on skincare and haircare products and often uses green, nature-inspired branding. Identify it.",
      options: ["L’Oréal", "Nivea", "Garnier", "Dove"],
      correctIndex: 2,
      imageUrl: "/uploads/logos-seed/logo-22-garnier.png",
    },
    {
      text: "This luxury brand is best known for:",
      options: ["Watches", "Handbags & fashion", "Shoes", "Perfumes only"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-23-hermes.png",
    },
    {
      text: "This logo belongs to which beauty brand?",
      options: ["Sugar Cosmetics", "Sephora", "SUGAR POP", "Swiss Beauty", "SERY Cosmetics", "Smashbox"],
      correctIndex: 0,
      imageUrl: "/uploads/logos-seed/logo-24-sugar.png",
    },
    {
      text: "This iconic logo represents which DJ?",
      options: ["Alan Walker", "Marshmello", "DJ Snake", "Avicii"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-25-marshmello.png",
    },
    {
      text: "This logo belongs to which fantasy sports platform?",
      options: ["MPL", "Dream11", "My11Circle", "FanFight"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-26-dream11.png",
    },
    {
      text: "This character is popularly known as:",
      options: ["Doraemon", "Hello Kitty", "Pikachu", "Barbie"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-27-hello-kitty.png",
    },
    {
      text: "This logo belongs to which kids’ content brand?",
      options: ["BabyBus", "ChuChu TV", "Cocomelon", "Pinkfong"],
      correctIndex: 2,
      imageUrl: "/uploads/logos-seed/logo-28-cocomelon.png",
    },
    {
      text: "This telecom brand is:",
      options: ["Jio", "Vodafone", "Airtel", "BSNL"],
      correctIndex: 2,
      imageUrl: "/uploads/logos-seed/logo-29-airtel.png",
    },
    {
      text: "This luxury brand logo represents:",
      options: ["Omega", "Titan", "Rolex", "Fossil"],
      correctIndex: 2,
      imageUrl: "/uploads/logos-seed/logo-30-rolex.png",
    },
    {
      text: "This logo belongs to which fashion brand?",
      options: ["Zara", "Gucci", "Balenciaga", "H&M"],
      correctIndex: 2,
      imageUrl: "/uploads/logos-seed/logo-31-balenciaga.png",
    },
    {
      text: "This mascot is associated with:",
      options: ["Nestle", "Amul", "Britannia", "Mother Dairy"],
      correctIndex: 1,
      imageUrl: "/uploads/logos-seed/logo-32-amul.png",
    },
  ],
};

// ─── Seed runner ──────────────────────────────────────────────────────────────
const seed = async () => {
  await connectDB();
  console.log("\n🌱  Starting seed...\n");

  // 1. Categories
  let catCount = 0;
  for (const cat of CATEGORIES) {
    await Category.findOneAndUpdate(
      { slug: cat.slug },
      cat,
      { upsert: true, new: true }
    );
    catCount++;
  }
  console.log(`✅  Upserted ${catCount} categories`);

  // 2. Questions
  let qCount = 0;
  for (const [categoryId, questions] of Object.entries(QUESTIONS)) {
    if (categoryId === "squid-game") {
      await Question.deleteMany({ categoryId: "squid-game" });
    }
    if (categoryId === "sports") {
      await Question.deleteMany({ categoryId: "sports" });
    }
    for (const q of questions) {
      await Question.findOneAndUpdate(
        { categoryId, text: q.text },
        { ...q, categoryId, timeLimit: q.timeLimit != null ? q.timeLimit : 10, isActive: true },
        { upsert: true, new: true }
      );
      qCount++;
    }
    // Update category questionCount
    const total = await Question.countDocuments({ categoryId, isActive: true });
    await Category.findOneAndUpdate({ slug: categoryId }, { questionCount: total });
  }
  console.log(`✅  Upserted ${qCount} questions`);

  // 3. Demo users
  const demoUsers = [
    { username: "DemoPlayer",  email: "demo@quizup.com",    password: "demo1234", country: "🇺🇸", bio: "Demo player account" },
    { username: "Player2Demo", email: "player2@quizup.com", password: "demo1234", country: "🇬🇧", bio: "Second demo account for testing" },
  ];

  for (const u of demoUsers) {
    const existing = await User.findOne({ email: u.email });
    if (!existing) {
      const passwordHash = await User.hashPassword(u.password);
      await User.create({
        username: u.username,
        email: u.email,
        passwordHash,
        bio: u.bio,
        country: u.country,
        displayName: u.username,
      });
      console.log(`✅  Created demo user: ${u.email} / ${u.password}`);
    } else {
      console.log(`⏭️   Demo user already exists: ${u.email}`);
    }
  }

  // 4. Admin account (Quiz CMS)
  const adminEmail = "admin@quiz.com";
  const adminPassword = "admin123";
  const adminHash = await User.hashPassword(adminPassword);
  const adminExisting = await User.findOne({ email: adminEmail });
  if (!adminExisting) {
    await User.create({
      username: "admin",
      email: adminEmail,
      passwordHash: adminHash,
      displayName: "Admin",
      role: "admin",
    });
    console.log(`✅  Created admin: ${adminEmail} / ${adminPassword}`);
  } else {
    await User.findOneAndUpdate(
      { email: adminEmail },
      { passwordHash: adminHash, role: "admin", username: "admin" }
    );
    console.log(`✅  Ensured admin account: ${adminEmail} / ${adminPassword}`);
  }

  console.log("\n🎉  Seed complete!\n");
  process.exit(0);
};

seed().catch((err) => {
  console.error("❌  Seed failed:", err);
  process.exit(1);
});
